/* DO NOT EDIT THIS FILE - it is machine generated */
#include <com_jacob_ndk_demo_jni_MathUtils.h>

JNIEXPORT jint JNICALL Java_com_jacob_ndk_demo_jni_MathUtils_square
  (JNIEnv *env, jclass object, jint num)
  {
        return num*num;
  }