/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jacob_ndk_demo_jni_MathUtils */

#ifndef _Included_com_jacob_ndk_demo_jni_MathUtils
#define _Included_com_jacob_ndk_demo_jni_MathUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jacob_ndk_demo_jni_MathUtils
 * Method:    square
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_jacob_ndk_demo_jni_MathUtils_square
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
